"""empty message

Revision ID: 2400d0790e21
Revises: a39e94829feb
Create Date: 2021-09-11 04:59:31.996282

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2400d0790e21'
down_revision = 'a39e94829feb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('show', sa.Column('future_show', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('show', 'future_show')
    # ### end Alembic commands ###
