"""empty message

Revision ID: 310b09c08fbf
Revises: 8999734d3787
Create Date: 2021-09-12 21:59:49.733454

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '310b09c08fbf'
down_revision = '8999734d3787'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('venue_profiles',
    sa.Column('venue_id', sa.Integer(), nullable=True),
    sa.Column('genre_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['genre_id'], ['genre.id'], ),
    sa.ForeignKeyConstraint(['venue_id'], ['artist.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('venue_profiles')
    # ### end Alembic commands ###
