"""empty message

Revision ID: 3e4b564062d0
Revises: da6c3f7f7845
Create Date: 2021-09-12 21:40:12.177642

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3e4b564062d0'
down_revision = 'da6c3f7f7845'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('venue_profiles', 'venue_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('venue_profiles', 'genre_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('venue_profiles', 'genre_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('venue_profiles', 'venue_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
