"""empty message

Revision ID: 4328ece753ea
Revises: 310b09c08fbf
Create Date: 2021-09-12 22:10:05.794197

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4328ece753ea'
down_revision = '310b09c08fbf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('artist_profiles', 'artist_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('artist_profiles', 'genre_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('artist_profiles', 'genre_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('artist_profiles', 'artist_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
