"""empty message

Revision ID: 4edd76ca9266
Revises: e7c18ab12ca3
Create Date: 2021-09-11 05:35:23.318238

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4edd76ca9266'
down_revision = 'e7c18ab12ca3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('show', 'future_show')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('show', sa.Column('future_show', sa.BOOLEAN(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
