"""empty message

Revision ID: 5ecc019f6ee4
Revises: f795f50c8e2d
Create Date: 2021-09-12 22:23:57.854775

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5ecc019f6ee4'
down_revision = 'f795f50c8e2d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('venue_profiles_venue_id_fkey', 'venue_profiles', type_='foreignkey')
    op.create_foreign_key(None, 'venue_profiles', 'venue', ['venue_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'venue_profiles', type_='foreignkey')
    op.create_foreign_key('venue_profiles_venue_id_fkey', 'venue_profiles', 'artist', ['venue_id'], ['id'])
    # ### end Alembic commands ###
