"""empty message

Revision ID: 8999734d3787
Revises: c9f399bbd677
Create Date: 2021-09-12 21:58:00.616973

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8999734d3787'
down_revision = 'c9f399bbd677'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('venue_profiles', 'venue_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('venue_profiles', 'genre_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('venue_profiles', 'genre_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('venue_profiles', 'venue_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
