"""empty message

Revision ID: 97ffe91af0af
Revises: 4edd76ca9266
Create Date: 2021-09-12 02:57:42.211271

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '97ffe91af0af'
down_revision = '4edd76ca9266'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('venue_profiles',
    sa.Column('venue_id', sa.Integer(), nullable=False),
    sa.Column('genre_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['genre_id'], ['genre.id'], ),
    sa.ForeignKeyConstraint(['venue_id'], ['artist.id'], ),
    sa.PrimaryKeyConstraint('venue_id', 'genre_id')
    )
    op.drop_constraint('genre_venue_id_fkey', 'genre', type_='foreignkey')
    op.drop_column('genre', 'venue_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('genre', sa.Column('venue_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('genre_venue_id_fkey', 'genre', 'venue', ['venue_id'], ['id'])
    op.drop_table('venue_profiles')
    # ### end Alembic commands ###
