"""empty message

Revision ID: a46f8718304a
Revises: eca1ea016e78
Create Date: 2021-09-12 22:59:34.675660

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a46f8718304a'
down_revision = 'eca1ea016e78'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'artist_profiles', ['artist_id', 'genre_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'artist_profiles', type_='unique')
    # ### end Alembic commands ###
