"""empty message

Revision ID: c152ec36d041
Revises: 2400d0790e21
Create Date: 2021-09-11 05:11:28.310235

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c152ec36d041'
down_revision = '2400d0790e21'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('genre', sa.Column('venue_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'genre', 'venue', ['venue_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'genre', type_='foreignkey')
    op.drop_column('genre', 'venue_id')
    # ### end Alembic commands ###
