"""empty message

Revision ID: c9f399bbd677
Revises: 3e4b564062d0
Create Date: 2021-09-12 21:50:42.326074

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c9f399bbd677'
down_revision = '3e4b564062d0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('venue_profiles', 'venue_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('venue_profiles', 'genre_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('venue_profiles', 'genre_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('venue_profiles', 'venue_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
