"""empty message

Revision ID: eb6290f80783
Revises: 3357336d3d6e
Create Date: 2021-09-12 20:18:40.441636

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eb6290f80783'
down_revision = '3357336d3d6e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('venue_profiles')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('venue_profiles',
    sa.Column('venue_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('genre_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['genre_id'], ['genre.id'], name='venue_profiles_genre_id_fkey'),
    sa.ForeignKeyConstraint(['venue_id'], ['artist.id'], name='venue_profiles_venue_id_fkey'),
    sa.PrimaryKeyConstraint('venue_id', 'genre_id', name='venue_profiles_pkey')
    )
    # ### end Alembic commands ###
