"""empty message

Revision ID: eca1ea016e78
Revises: 1dd6eac60351
Create Date: 2021-09-12 22:50:02.969961

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eca1ea016e78'
down_revision = '1dd6eac60351'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'venue_profiles', ['venue_id', 'genre_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'venue_profiles', type_='unique')
    # ### end Alembic commands ###
